# Set global configuration arguments
cask_args appdir: "/Applications"

tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/bundle"

###############################################################################
# CLI tools                                                                   #
###############################################################################

# Cask dependencies
brew "mas"

brew "awscli"
brew "ctags"
brew "duti"
brew "fzf"
brew "gh"
brew "htop"
brew "rg"
brew "ssh-copy-id"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"

###############################################################################
# Cask GUI Applications                                                       #
###############################################################################

# Password Manager & Authenticator
cask "bitwarden"
cask "authy"

# Dev Tools
cask "CotEditor"
cask "visual-studio-code"
cask "ngrok"
cask "postman"
cask "docker"

# DB
cask "sequel-pro"
cask "studio-3t"

# Browsers
cask "google-chrome"
cask "firefox"

# Input Method
cask "google-japanese-ime"
# TODO: open /usr/local/Caskroom/google-japanese-ime/latest/GoogleJapaneseInput.pkg
cask "mcbopomofo"
# TODO: open /usr/local/Caskroom/mcbopomofo/2.5/McBopomofoInstaller.app

# Others
cask "obsidian"
cask "spotify"
cask "dropbox"
cask "zoom"
cask "slack"

###############################################################################
# MAS Applications                                                            #
###############################################################################

mas "LINE", id: 539883307
mas "Magnet", id: 441258766
